import type { Property } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Modern Downtown Loft',
    description: 'A stylish and modern loft in the heart of the city. Perfect for young professionals. Fully furnished with high-end appliances and a stunning view of the skyline.',
    price: 2500,
    city: 'Metropolis',
    images: ['https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg', 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg', 'https://images.pexels.com/photos/2635038/pexels-photo-2635038.jpeg'],
    propertyType: 'Apartment',
    landlordId: 'landlord1',
    amenities: ['WiFi', 'Parking', 'Gym', 'Pool'],
  },
  {
    id: '2',
    title: 'Cozy Suburban House',
    description: 'A beautiful family house in a quiet suburban neighborhood. Features a large backyard, a modern kitchen, and is close to schools and parks.',
    price: 3200,
    city: 'Suburbia',
    images: ['https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg', 'https://images.pexels.com/photos/2089698/pexels-photo-2089698.jpeg', 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg'],
    propertyType: 'House',
    landlordId: 'landlord2',
    amenities: ['Garage', 'Garden', 'Pet Friendly'],
  },
  {
    id: '3',
    title: 'Luxury Beachfront Villa',
    description: 'Experience luxury living with this stunning beachfront villa. Private beach access, an infinity pool, and breathtaking ocean views.',
    price: 7500,
    city: 'Coastal City',
    images: ['https://images.pexels.com/photos/1287460/pexels-photo-1287460.jpeg', 'https://images.pexels.com/photos/2440471/pexels-photo-2440471.jpeg', 'https://images.pexels.com/photos/221457/pexels-photo-221457.jpeg'],
    propertyType: 'Villa',
    landlordId: 'landlord3',
    amenities: ['Pool', 'Beach Access', 'Parking', 'WiFi'],
  },
  {
    id: '4',
    title: 'Charming Studio Apartment',
    description: 'A compact and charming studio in a vibrant area. Close to public transport, cafes, and shops. Ideal for a single person or a student.',
    price: 1500,
    city: 'Metropolis',
    images: ['https://images.pexels.com/photos/271643/pexels-photo-271643.jpeg', 'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg'],
    propertyType: 'Studio',
    landlordId: 'landlord1',
    amenities: ['WiFi', 'Kitchenette'],
  },
  {
    id: '5',
    title: 'Spacious Family Home',
    description: 'A large and spacious home perfect for a growing family. Includes 4 bedrooms, 3 bathrooms, and a two-car garage.',
    price: 4200,
    city: 'Suburbia',
    images: ['https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg', 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg'],
    propertyType: 'House',
    landlordId: 'landlord2',
    amenities: ['Garage', 'Garden', 'Pet Friendly', 'Fireplace'],
  },
  {
    id: '6',
    title: 'Penthouse with Rooftop Terrace',
    description: 'An exclusive penthouse apartment with a private rooftop terrace offering 360-degree city views. The ultimate urban living experience.',
    price: 9000,
    city: 'Metropolis',
    images: ['https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg', 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg'],
    propertyType: 'Apartment',
    landlordId: 'landlord3',
    amenities: ['Pool', 'Gym', 'Rooftop Terrace', 'Concierge'],
  },
   {
    id: '7',
    title: 'Quiet Riverside Cottage',
    description: 'A peaceful cottage located by the river, away from the hustle and bustle. Perfect for nature lovers and those seeking tranquility.',
    price: 2100,
    city: 'Rivertown',
    images: ['https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg', 'https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg'],
    propertyType: 'Cottage',
    landlordId: 'landlord4',
    amenities: ['Garden', 'Pet Friendly', 'Fireplace'],
  },
  {
    id: '8',
    title: 'Affordable City Center Apartment',
    description: 'An affordable 2-bedroom apartment in the city center. A great choice for students or young couples starting out.',
    price: 1800,
    city: 'Metropolis',
    images: ['https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg', 'https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg'],
    propertyType: 'Apartment',
    landlordId: 'landlord5',
    amenities: ['WiFi', 'Parking'],
  },
];
